install:
	sudo apt-get -y update
	sudo apt-get install -y python3-pip
	pip3 install --upgrade pip
	sudo pip3 install -r requirements.txt
	(cd /opt/npset/mylib/playLib; make)
	echo HI
	echo python -m jupyter etc ... ...
