install:
	sudo apt-get -y update
	sudo apt-get install -y python3-pip
	pip3 install --upgrade pip
	pip3 install jupyter
	pip3 install --user pika
	pip3 install --user matplotlib
	pip3 install --user s3fs
	pip3 install --user awscli
	(cd /opt/npset/mylib/playLib; make)
	echo HI
	echo python -m jupyter etc ... ...
