hello:
	echo hello in the container

list:
	rclone listremotes

test:
	rclone copy /data/log et-data:/ga-et-data/steffi/log -P


config_aws:
	aws configure


##
## AWS Access Key ID [None]: AKIAIOSFODNN7EXAMPLE
## AWS Secret Access Key [None]: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
## Default region name [None]: us-west-2
## Default output format [None]: json
