version: '3'

services:
  rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
  qcog:
    image: tbutzer/cogxfer
  tony:
    image: tbutzer/bash-tester
    deploy:
      placement:
        constraints:
          - node.role == manager


