local-jupyter:
	python3 -m notebook --allow-root --ip="0.0.0.0" --NotebookApp.token='yaml' --port=8080 



git:
	(cd npset; make)


install:
	sudo apt-get update
	sudo apt-get install python3-pip
	pip3 install --upgrade pip
	pip3 install jupyter
	pip3 install --user pika
	pip3 install --user matplotlib
	pip3 install --user s3fs
	pip3 install --user awscli
	echo HI
	echo python -m jupyter etc ... ...
