version: '3'
services:
  web:
    image: redis
    ports:
      - "6379:6379"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 172.31.48.237:24224
        tag: redis.service

